name: Sudo
version: @version@
description: Execute commands as op
main: hazae41.minecraft.sudo.bukkit.SudoBukkitPlugin
author: Hazae41

commands:
  sudo:
    usage: /sudo <command>
    permission: sudo.sudo
    description: Execute command as op + all permissions
  asop:
    usage: /asop <command>
    permission: sudo.asop
    description: Execute command as op
  su:
    usage: /su <target>
    permission: sudo.su
    description: Execute commands as another player